### ISSUE TITLE
FAQ Question 1 - possible error

### ISSUE THREAD

**Issue by mdeamico** [bertcarnell/lhs#23]
FAQ question 1 reads as follows. Note line 35 with "Latin hypercube on [1,10]" and line 46 transforming the distribution. https://github.com/bertcarnell/lhs/blob/a743f244041067038d664a312cfcffbcab039abf/vignettes/lhs_faq.Rmd#L33-L46

On line 46, Should the maximum in qunif be 10?  i.e. `Y[,1] <- qunif(Y[,1], 1, 10)`

**Comment by bertcarnell** [comment]
Agreed.  Thank-you!

**Comment by bertcarnell** [comment]
Fixed in https://github.com/bertcarnell/lhs/commit/2d82655aaacf680fe0bd6dc574a774dcc552bca2
