### ISSUE TITLE
Set minimal required R version to 3.3.0

### ISSUE THREAD

**Issue by mllg** [bertcarnell/lhs#24]
I've just tested lhs with 3.3.3, it seems to work fine. If you'd change the minimal required version, this would be one less hoop to jump through in our CI setup for mlr3.

**Comment by bertcarnell** [comment]
Could you tell me more about what this change would save you?  I appreciate that you've tested it back with R-3.3.3, but I would also have to do the same testing.  With the number of reverse dependencies on `lhs`, a new release, even for something this simple, is not an easy job.
