### ISSUE TITLE
Documentation createBoseBushl

### ISSUE THREAD

**Issue by ugroempi** [bertcarnell/lhs#26]
Hi Rob,
in the documentation of createBoseBushl, it is stated that (ncol=) k <= lambda*q+1, but there is an error message with ncol>lambda*q (I believe that the "+1" only holds for the special case with lambda=2). 
Best, Ulrike

P.S.: By the way, Theorem 6.28 of Hedayat, Sloane and Stufken discussed a Bose Bush construction with a larger number of factors (e.g. 13 instead of 9 for q=lambda=3, or 40 instead of 27 for q=3, lambda=9), i.e. the Owen code seems to miss out on opportunities.

**Comment by bertcarnell** [comment]
Ulrike,

Thanks for pointing this out.  I can also reproduce the error and I'm working on a solution or documentation fix.

```{r}
B <- createBoseBushl(q = 2^2, ncol = 2*2^2, lambda = 2, bRandom = FALSE)  # Passes
B <- createBoseBushl(q = 2^2, ncol = 2*2^2+1, lambda = 2, bRandom = FALSE)  # Fails
```

**Comment by bertcarnell** [comment]
This is fixed in https://github.com/bertcarnell/lhs/commit/2b000370b7972a7218ea99670f3ea86fabbe58f6.  (ncol=) k = lambda*q+1 is now permitted.  I could not find a reason why the "+1" only holds for the special case with lambda=2 in the original code.  I have ordered the reference you cited, so I'll look there too.

**Comment by ugroempi** [comment]
Rob, 
thanks for fixing this so fast! I don't see any more why I thought that the special case lambda=2 is relevant, so don't waste time on that. The extended number of factors from Hedayat, Sloane and Stufken would be worthwhile, however; but it would require implementing a recursive approach (that is presumably not in the Owen code on which you based your functions).
