### ISSUE TITLE
function 'Rcpp_precious_remove' not provided by package 'Rcpp'

### ISSUE THREAD

**Issue by Paudelrajan** [bertcarnell/lhs#53]
Getting the issue as shown below whenever I run randomLHS function. I tried checking with example provided in the function as well but doesn't work.

Version: RStudio 2023.06.0+421 

![image](https://github.com/bertcarnell/lhs/assets/20872480/9eaa2b3e-1c42-4018-86b7-f78633469a9e)

**Comment by bertcarnell** [comment]
I tried re-creating with R 4.2.0 and RStudio 2022.02.3 build 492, but did not get an error.

@Paudelrajan Have you tried to clean up the warning in reading your file?  Do you know what `ncol(par.range)` is returning?

```
temp_file_name <- tempfile()
write.csv(mtcars, file = temp_file_name)

require(lhs)
require(EnvStats)

nsmpl <- 100
par.range <- read.csv(temp_file_name, row.names = 1)
fu.pars <- au.pars <- randomLHS(nsmpl, ncol(par.range))
```

I will upgrade to R4.3.0 and RStudio to see if that causes the issue.

**Comment by bertcarnell** [comment]
CRAN results are not showing any problems with the unit tests or examples

https://cran.r-project.org/web/checks/check_results_lhs.html

**Comment by bertcarnell** [comment]
After upgrading, I'm still not able to reproduce the error.  

@Paudelrajan Can you send the file?  Can you try something simpler like `lhs::randomLHS(5, 4)`?

```
> R.Version()$version.string
[1] "R version 4.3.0 (2023-04-21 ucrt)"
> R.Version()$version.string
[1] "R version 4.3.0 (2023-04-21 ucrt)"
> packageVersion("lhs")
[1] ‘1.1.6’
> packageVersion("Rcpp")
[1] ‘1.0.10’
> packageVersion("EnvStats")
[1] ‘2.7.0’
> rstudioapi::versionInfo()$long_version
[1] "2023.06.0+421"
```

**Comment by Paudelrajan** [comment]
I had tried with simpler codes and also by updating R as well, but in vain. Uninstalling and installing lhs package worked. Thanks.
